@BASE_URL=https://localhost:7001

GET {{BASE_URL}}/offset?page=1&pageSize=4
User-Agent: rest-client
Content-Type: application/json
Accept: application/json

###

GET {{BASE_URL}}/cursor?limit=4
User-Agent: rest-client
Content-Type: application/json
Accept: application/json

###

@NEXT_CURSOR=eyJEYXRlIjoiMjAyNS0xMC0xNSIsIkxhc3RJZCI6ImZmYzlmOTMzLTM0YmMtNDIxOS1hNmFjLWZjNmU0NDk0MzEyOCJ9
GET {{BASE_URL}}/cursor?limit=4&cursor={{NEXT_CURSOR}}