@BASE_URL=https://localhost:7001

GET {{BASE_URL}}/offset?page=1&pageSize=4
User-Agent: rest-client
Content-Type: application/json
Accept: application/json

###

GET {{BASE_URL}}/cursor?limit=4
User-Agent: rest-client
Content-Type: application/json
Accept: application/json

###

@NEXT_CURSOR=eyJEYXRlIjoiMjAyNS0xMi0yMyIsIkxhc3RJZCI6IjAxOWI0YTBjLTU1MTQtNzJjOS1hYmQyLWNmNWMwMWQ2NjZmYyIsIlZlcnNpb24iOjF9
GET {{BASE_URL}}/cursor?limit=4&cursor={{NEXT_CURSOR}}